// "use client";

// import {
//   Check,
//   Copy,
//   MessageCircle,
//   X,
// } from "lucide-react";
// import { useState } from "react";

// type ShareDialogProps = {
//   shareUrl: string;
//   onClose: () => void;
// };

// export default function ShareDialog({
//   shareUrl,
//   onClose,
// }: ShareDialogProps) {
//   const [copied, setCopied] =
//     useState(false);

//   const handleCopy = async () => {
//     await navigator.clipboard.writeText(
//       shareUrl,
//     );

//     setCopied(true);

//     window.setTimeout(() => {
//       setCopied(false);
//     }, 1800);
//   };

//   const handleWhatsApp = () => {
//     const message =
//       `I'd like to share a Sutradhara workspace with you:\n\n${shareUrl}`;

//     const whatsappUrl =
//       `https://wa.me/?text=${encodeURIComponent(
//         message,
//       )}`;

//     window.open(
//       whatsappUrl,
//       "_blank",
//       "noopener,noreferrer",
//     );
//   };

//   return (
//     <div
//       className="fixed inset-0 z-[100] flex items-center justify-center bg-black/65 px-5 backdrop-blur-sm"
//       onMouseDown={(event) => {
//         if (
//           event.target ===
//           event.currentTarget
//         ) {
//           onClose();
//         }
//       }}
//     >
//       <div className="w-full max-w-md overflow-hidden rounded-2xl border border-[#A9854F]/20 bg-[#17130F] shadow-2xl">
//         <div className="flex items-center justify-between border-b border-[#A9854F]/10 px-5 py-4">
//           <div>
//             <p className="font-mono text-[8px] uppercase tracking-[0.24em] text-[#A9854F]">
//               Sutradhara
//             </p>

//             <h2 className="mt-1 font-serif text-xl text-[#F0E6D2]">
//               Share workspace
//             </h2>
//           </div>

//           <button
//             type="button"
//             onClick={onClose}
//             className="flex h-8 w-8 items-center justify-center rounded-lg text-[#B39A72]/60 transition hover:bg-[#A9854F]/10 hover:text-[#F0E6D2]"
//           >
//             <X size={15} />
//           </button>
//         </div>

//         <div className="p-5">
//           <p className="text-xs leading-6 text-[#B39A72]/60">
//             Anyone with this link can open the
//             shared workspace.
//           </p>

//           <div className="mt-5 flex items-center gap-2 rounded-xl border border-[#A9854F]/15 bg-[#0F0D0A] p-2">
//             <input
//               readOnly
//               value={shareUrl}
//               className="min-w-0 flex-1 bg-transparent px-2 text-[11px] text-[#D6C4A3] outline-none"
//             />

//             <button
//               type="button"
//               onClick={handleCopy}
//               className="flex shrink-0 items-center gap-2 rounded-lg bg-[#A9854F] px-3 py-2 text-[9px] uppercase tracking-wider text-[#0F0D0A] transition hover:bg-[#C49A5A]"
//             >
//               {copied ? (
//                 <>
//                   <Check size={13} />
//                   Copied
//                 </>
//               ) : (
//                 <>
//                   <Copy size={13} />
//                   Copy
//                 </>
//               )}
//             </button>
//           </div>

//           <button
//             type="button"
//             onClick={handleWhatsApp}
//             className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[#A9854F]/15 bg-[#111311] px-4 py-3 text-[10px] uppercase tracking-wider text-[#D6C4A3] transition hover:border-[#A9854F]/30 hover:bg-[#211A13]"
//           >
//             <MessageCircle size={14} />
//             Share on WhatsApp
//           </button>

//           <p className="mt-4 text-center font-mono text-[8px] uppercase tracking-[0.18em] text-[#827B70]">
//             Link generated by Sutradhara
//           </p>
//         </div>
//       </div>
//     </div>
//   );
// }

"use client";

import {
  Check,
  Copy,
  MessageCircle,
  X,
} from "lucide-react";
import { useState } from "react";

type ShareDialogProps = {
  shareUrl: string;
  onClose: () => void;
};

export default function ShareDialog({
  shareUrl,
  onClose,
}: ShareDialogProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (!shareUrl) {
      return;
    }

    await navigator.clipboard.writeText(shareUrl);

    setCopied(true);

    window.setTimeout(() => {
      setCopied(false);
    }, 1800);
  };

  const handleWhatsApp = () => {
    if (!shareUrl) {
      return;
    }

    const message =
      `I'd like to share a Sutradhara workspace with you:\n\n${shareUrl}`;

    const whatsappUrl =
      `https://wa.me/?text=${encodeURIComponent(message)}`;

    window.open(
      whatsappUrl,
      "_blank",
      "noopener,noreferrer",
    );
  };

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center bg-black/65 px-5 backdrop-blur-sm"
      onMouseDown={(event) => {
        if (
          event.target === event.currentTarget
        ) {
          onClose();
        }
      }}
    >
      <div className="w-full max-w-md overflow-hidden rounded-2xl border border-[#A9854F]/20 bg-[#17130F] shadow-2xl">
        <div className="flex items-center justify-between border-b border-[#A9854F]/10 px-5 py-4">
          <div>
            <p className="font-mono text-[8px] uppercase tracking-[0.24em] text-[#A9854F]">
              Sutradhara
            </p>

            <h2 className="mt-1 font-serif text-xl text-[#F0E6D2]">
              Share workspace
            </h2>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="flex h-8 w-8 items-center justify-center rounded-lg text-[#B39A72]/60 transition hover:bg-[#A9854F]/10 hover:text-[#F0E6D2]"
            aria-label="Close share dialog"
          >
            <X size={15} />
          </button>
        </div>

        <div className="p-5">
          <p className="text-xs leading-6 text-[#B39A72]/60">
            Anyone with this link can open the
            shared workspace.
          </p>

          <div className="mt-5 flex items-center gap-2 rounded-xl border border-[#A9854F]/15 bg-[#0F0D0A] p-2">
            <a
              href={shareUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="min-w-0 flex-1 truncate px-2 text-[11px] text-[#D6C4A3] underline decoration-[#A9854F]/40 underline-offset-4 transition hover:text-[#F0E6D2] hover:decoration-[#A9854F]"
              title={shareUrl}
            >
              {shareUrl}
            </a>

            <button
              type="button"
              onClick={handleCopy}
              disabled={!shareUrl}
              className="flex shrink-0 items-center gap-2 rounded-lg bg-[#A9854F] px-3 py-2 text-[9px] uppercase tracking-wider text-[#0F0D0A] transition hover:bg-[#C49A5A] disabled:cursor-not-allowed disabled:opacity-50"
            >
              {copied ? (
                <>
                  <Check size={13} />
                  Copied
                </>
              ) : (
                <>
                  <Copy size={13} />
                  Copy
                </>
              )}
            </button>
          </div>

          <button
            type="button"
            onClick={handleWhatsApp}
            disabled={!shareUrl}
            className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[#A9854F]/15 bg-[#111311] px-4 py-3 text-[10px] uppercase tracking-wider text-[#D6C4A3] transition hover:border-[#A9854F]/30 hover:bg-[#211A13] disabled:cursor-not-allowed disabled:opacity-50"
          >
            <MessageCircle size={14} />
            Share on WhatsApp
          </button>

          <p className="mt-4 text-center font-mono text-[8px] uppercase tracking-[0.18em] text-[#827B70]">
            Link generated by Sutradhara
          </p>
        </div>
      </div>
    </div>
  );
}